### ISSUE TITLE
Can't performance a search

### ISSUE THREAD

**Issue by stemy2** [Virusmater/plugin.audio.kxmxpxtx.bandcamp#10]
When i'm performing a search, i have nothing but a "bandcamp error", even if what i search actually exists on bandcamp.
[The log](HTTPS://paste.kodi.tv/apihevehew)

**Comment by Virusmater** [comment]
Hello, this version of the plugin wasn't updated for years.
Currently there is a different fork in the Kodi repo:
https://github.com/molzy/plugin.audio.kxmxpxtx.bandcamp
